# Generated by Django 5.0 on 2023-12-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeuser',
            name='name',
            field=models.CharField(default='revie', max_length=225),
        ),
    ]
